### ISSUE TITLE
Bot posts code snippets in Discord chat with nice formatting and highlighting

### ISSUE THREAD

**Issue by satu** [stuck-overflow/ferris-bot#18]

**Comment by Ilovekitty** [comment]
did you get the bot sending text to channels yet?

**Comment by satu** [comment]
> did you get the bot sending text to channels yet?

tracked in issue #3 , I have to finish the auth part (requires user interaction to get token from Twitch)

**Comment by ed-fish** [comment]
Can we close this issue now - as solved in issue #4

**Comment by satu** [comment]
agreed. closing.
