### ISSUE TITLE
Refactor configuration / credentials file

### ISSUE THREAD

**Issue by satu** [stuck-overflow/ferris-bot#23]
As we add functionalities, we now have an inconsistent way of storing credentials (twitchauth.toml + .token).

We need one settings file only, in which we store credentials for both Discord and Twitch, as well as other params like login name, channel id, etc.

**Comment by ed-fish** [comment]
Yes - let's make sure we check the readme each merge also to ensure the argparser is setup correctly with new config files etc.

**Comment by satu** [comment]
done! pending review already https://github.com/stuck-overflow/ferris-bot/pull/26
