### ISSUE TITLE
Add a rustfmt.toml to this project

### ISSUE THREAD

**Issue by satu** [stuck-overflow/ferris-bot#38]
Start by adding https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#imports_granularity

**Comment by satu** [comment]
Apparently imports_granularity is only available when using "unstable_features", which as I understand it are only enabled in rustfmt nightly. I managed to make it work by running `cargo +nightly fmt` and it worked fine.

@silen-z do you know if there is a way of semi-automatically indicate that this repo requires nightly rustfmt? since we develop this in multiple different environments, it would be nice to find an easy way for everyone to run the right thing just by running `cargo fmt`.

**Comment by silen-z** [comment]
I know other people have exactly this problem, but unfortunately I don't know a solution. You could override the default toolchain but that would affect all cargo commands.

**Comment by satu** [comment]
can I override the toolchain in the Cargo.toml ? I don't mind moving the project to use nightly as long as this happens semi-automatically for whomever checks out the repo and tries to build

**Comment by nyxkrage** [comment]
You can use a `rust-toolchain` file
[https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)
