### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Miboch** [stuck-overflow/ferris-bot#7]
This is a public repo but what license is it under? Thanks.

**Comment by ed-fish** [comment]
GNU or Apache would be preferred but Twitch IRC uses MIT so perhaps we should continue to use that licence:

https://github.com/robotty/twitch-irc-rs/blob/master/LICENSE

**Comment by satu** [comment]
We don't have to (GPL is the "viral" one), but I like the Apache/MIT licence so let's go for it.

**Comment by ed-fish** [comment]
MIT licence added
